# Generated by Django 5.0.4 on 2024-05-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pushbyt", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animation",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
