# Generated by Django 5.0.4 on 2024-05-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pushbyt", "0006_apitoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitoken",
            name="expires_in",
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
