# Generated by Django 5.0.4 on 2024-05-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pushbyt", "0008_alter_animation_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animation",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
