# Generated by Django 5.0.4 on 2024-10-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushbyt', '0011_alter_animation_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='source',
            field=models.CharField(choices=[('static', 'Static'), ('rays', 'Rays'), ('spotify', 'Spotify'), ('timer', 'Timer'), ('doorbell', 'Doorbell'), ('radar', 'Radar')], default='static', max_length=20),
        ),
    ]
